
kind: Service
apiVersion: v1
metadata:
  name: devchatdemo
spec:
  type: NodePort
  selector:
    app: devchatdemo
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devchatdemo
  labels:
    app: devchatdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devchatdemo
      track: stable
  template:
    metadata:
      labels:
        app: devchatdemo
        track: stable
    spec:
      containers:
      - name: devchatdemo
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
